#!/usr/bin/env bash

GIT_HOOKS=".git/hooks"
MISC_HOOKS="$GOPATH/src/github.com/atlassian/terraform-provider-artifactory/misc/hooks"

for file in $(ls $MISC_HOOKS/ | grep -v \\.)
do

cat > $GIT_HOOKS/$file << EOF
#!/usr/bin/env bash
$MISC_HOOKS/$file
exit $?
EOF

done